version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.0.3
  
jobs:
  build-and-test:
    working_directory: ~/test-repository/ISA-project
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:9.6.2-alpine
      
        auth:
          username: postgres
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: booking-isa         

    steps:
      - checkout:
          path: ~/test-repository
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=KNatali_ISA-Project-Booking-System

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          name: deploy-back
          app-name: isa-fishing
          requires:
            - build-and-test
      - heroku/deploy-via-git:
          name: deploy-front
          app-name: angular-fishing
          requires:
            - deploy-back